[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "pywc"
version = "1.0.0"

[project.scripts]
pywc = "pywc.__main__:main"

[too.setuptools.packages.find]
where = ["."]